<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Please enter your username or email</name>
   <tag></tag>
   <elementGuidId>72fa9be5-c05a-4f9e-aa19-785c1e242eb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='um_field_298_username']/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.um-field-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>77a5b79b-9952-4488-92de-dc0732cd2ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-field-error</value>
      <webElementGuid>b1628361-b4a8-4be1-9712-f074891d66dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter your username or email</value>
      <webElementGuid>5018cf82-339a-4f3a-82e0-454fd1e1c089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;um_field_298_username&quot;)/div[@class=&quot;um-field-error&quot;]</value>
      <webElementGuid>375a54bc-7422-48cd-ae6a-09d0e4690978</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um_field_298_username']/div[3]</value>
      <webElementGuid>d722088a-1d28-4336-8e6d-73a14b1fef63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username or E-mail'])[1]/following::div[3]</value>
      <webElementGuid>6de46d73-132f-443a-bfbd-6c138af9e91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[4]/following::div[10]</value>
      <webElementGuid>d4da377c-266c-43d7-8c1b-22be33df8b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::div[1]</value>
      <webElementGuid>9c9e73c0-34ab-472a-8e31-c63d4d909a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter your password'])[1]/preceding::div[4]</value>
      <webElementGuid>9ce74582-b730-46b3-8146-2272fa96a061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please enter your username or email']/parent::*</value>
      <webElementGuid>8d17723b-c64c-49e3-b325-626ecd63d68f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/div/div/form/div/div/div/div[3]</value>
      <webElementGuid>a8eea636-e64e-4ccb-bd2e-71cb8ff3671a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Please enter your username or email' or . = 'Please enter your username or email')]</value>
      <webElementGuid>92fd0df6-e273-43c5-ba23-7bdc6f321f43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
