<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_user_password-298</name>
   <tag></tag>
   <elementGuidId>ae46ded9-1c04-4a78-8faf-9e2cab8300b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_password-298']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#user_password-298</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6f41822-d15e-48f5-bf03-807b6c7bb1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-form-field valid </value>
      <webElementGuid>3ee92b7b-ba4a-40a0-b6c7-851b22294331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>5af5ce25-0eff-4d8b-a2df-866fb153be35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_password-298</value>
      <webElementGuid>1c294769-cf0b-44c9-a71f-25410a1165ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_password-298</value>
      <webElementGuid>b6063d81-58ce-4f25-b584-1e68715baf27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>user_password</value>
      <webElementGuid>3e4549ec-9a09-493f-81d0-a7c43b1abb29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_password-298&quot;)</value>
      <webElementGuid>a64691f8-574e-4c38-acf6-a27ec62f2f25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_password-298']</value>
      <webElementGuid>f6454032-0f7b-41a6-b763-b049c3d18f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um_field_298_user_password']/div[2]/input</value>
      <webElementGuid>b93e0bd0-f1f0-4d02-8c4c-8bc818833da7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>954d2377-a53b-4ec1-aaa9-d8b7420c4a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'user_password-298' and @id = 'user_password-298']</value>
      <webElementGuid>f811e464-b05f-4a54-afca-bc7b6be8ff76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
