<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Filters_thehanger-icons-display-list</name>
   <tag></tag>
   <elementGuidId>56280eec-39fd-45b2-8a1d-50376aac161a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/div[2]/div/div/header/div/div/div/span[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.thehanger-icons-display-list</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b9bcb011-3fc9-4732-8eb5-fb8aff1daa07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>thehanger-icons-display-list</value>
      <webElementGuid>7e9a1db3-89fb-47c7-a875-ce0125ec536b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;small-12 large-9 columns&quot;]/div[@class=&quot;site-main-content-wrapper&quot;]/div[@class=&quot;shop_header_placeholder&quot;]/header[@class=&quot;woocommerce-archive-header&quot;]/div[@class=&quot;woocommerce-archive-header-inside&quot;]/div[@class=&quot;woocommerce-archive-header-tools site-secondary-font site-secondary-color&quot;]/div[@class=&quot;shop-tools&quot;]/span[@class=&quot;shop-display-list&quot;]/i[@class=&quot;thehanger-icons-display-list&quot;]</value>
      <webElementGuid>c9ed6991-09bb-4e8f-89d8-c2a73da65d6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div[2]/div/div/header/div/div/div/span[2]/i</value>
      <webElementGuid>3077b081-55d4-42be-9a1b-d182355cf975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/i</value>
      <webElementGuid>bac92451-eef3-44c7-92ce-bd6adee3423b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
