<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Rp45.000 Rp42.000</name>
   <tag></tag>
   <elementGuidId>52718627-ad8f-4775-a082-b7ea3e4659a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sticky_bottom_anchor']/ul/li[5]/div/div[2]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.product.type-product.post-14.status-publish.first.instock.product_cat-uncategorized.has-post-thumbnail.sale.featured.shipping-taxable.purchasable.product-type-simple.visible.animation_ready.animated > div.main-container > div.second-container > div.product_info > span.price</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>afc56afb-50b9-4a00-b5d6-86a1b5b4874e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>58c243c7-9196-4504-b11c-16329245678c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp45.000 Rp42.000</value>
      <webElementGuid>10bbbc8f-6c20-46e6-a330-30264b2c4baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sticky_bottom_anchor&quot;)/ul[@class=&quot;products columns-3 js_animated&quot;]/li[@class=&quot;product type-product post-14 status-publish first instock product_cat-uncategorized has-post-thumbnail sale featured shipping-taxable purchasable product-type-simple visible animation_ready animated&quot;]/div[@class=&quot;main-container&quot;]/div[@class=&quot;second-container&quot;]/div[@class=&quot;product_info&quot;]/span[@class=&quot;price&quot;]</value>
      <webElementGuid>b0f2405b-adfb-4370-a122-8fdbab1a97ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sticky_bottom_anchor']/ul/li[5]/div/div[2]/div/span</value>
      <webElementGuid>4ec3cdb8-f2ed-4959-a6d8-009c47233cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoodie with Zipper'])[2]/following::span[1]</value>
      <webElementGuid>abe3b05b-4ee4-4c46-ae49-f0ca59ecacae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sale!'])[4]/following::span[1]</value>
      <webElementGuid>2854bccb-f554-4ec1-b47a-316f6726828c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/div[2]/div/span</value>
      <webElementGuid>e6bc3e98-2f40-4df8-9737-321bf4f2efda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Rp45.000 Rp42.000' or . = 'Rp45.000 Rp42.000')]</value>
      <webElementGuid>c0ad9a73-76bb-4d12-bdab-94c36cb98247</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
