<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_Rp18.000</name>
   <tag></tag>
   <elementGuidId>c685cdda-14b3-486e-9e00-7e997acd44b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sticky_bottom_anchor']/ul/li[5]/div/div[2]/div/span/span/bdi</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.product.type-product.post-25.status-publish.first.instock.product_cat-uncategorized.has-post-thumbnail.shipping-taxable.purchasable.product-type-simple.visible.animation_ready.animated > div.main-container > div.second-container > div.product_info > span.price > span.woocommerce-Price-amount.amount > bdi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>b10b85e4-0052-4c33-853e-728bc94f4a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp18.000</value>
      <webElementGuid>4a7fdc94-303f-4a91-ba2a-cf6f92343551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sticky_bottom_anchor&quot;)/ul[@class=&quot;products columns-3 js_animated&quot;]/li[@class=&quot;product type-product post-25 status-publish first instock product_cat-uncategorized has-post-thumbnail shipping-taxable purchasable product-type-simple visible animation_ready animated&quot;]/div[@class=&quot;main-container&quot;]/div[@class=&quot;second-container&quot;]/div[@class=&quot;product_info&quot;]/span[@class=&quot;price&quot;]/span[@class=&quot;woocommerce-Price-amount amount&quot;]/bdi[1]</value>
      <webElementGuid>c2d5694d-31fa-4aa4-8dbc-d0b9a0a4d649</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sticky_bottom_anchor']/ul/li[5]/div/div[2]/div/span/span/bdi</value>
      <webElementGuid>01bd0942-c9e0-4886-9308-466b26b30a92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T-Shirt with Logo'])[1]/following::bdi[1]</value>
      <webElementGuid>69d1ba4f-0077-4d46-b5cd-c0ab1d30c646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New!'])[4]/following::bdi[1]</value>
      <webElementGuid>c52ac408-7a65-4ff1-afde-f431062783bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick View'])[4]/preceding::bdi[1]</value>
      <webElementGuid>fdc3ba4e-f9c8-412c-8da8-bc843e316b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='18.000']/parent::*</value>
      <webElementGuid>52b516ad-1bdc-41a4-87d6-4c11e9ae883d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/div[2]/div/span/span/bdi</value>
      <webElementGuid>624566a2-c276-4f93-a524-3b29bda17dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[(text() = 'Rp18.000' or . = 'Rp18.000')]</value>
      <webElementGuid>5ceeb930-6e25-4c0c-942a-c65cf8d7a74a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
