<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_New</name>
   <tag></tag>
   <elementGuidId>676871f7-0aec-4d59-87c4-994060098925</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sticky_bottom_anchor']/ul/li[4]/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.getbowtied_new_product</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9dad3f8e-59e3-479a-b68f-bf249d642121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>getbowtied_new_product</value>
      <webElementGuid>841b83c4-7fdd-4be4-a981-2567452b3453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New!</value>
      <webElementGuid>35920f8b-9093-41df-8204-921eabd26377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sticky_bottom_anchor&quot;)/ul[@class=&quot;products columns-3 js_animated&quot;]/li[@class=&quot;product type-product post-240 status-publish last instock product_cat-uncategorized has-post-thumbnail sale featured shipping-taxable purchasable product-type-simple visible animation_ready animated&quot;]/div[@class=&quot;main-container&quot;]/div[@class=&quot;product_image_wrapper&quot;]/div[@class=&quot;product_badges_wrapper&quot;]/span[@class=&quot;getbowtied_new_product&quot;]</value>
      <webElementGuid>90c18d4e-eb5d-4fc6-a529-d2ed67bcad4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>98c0b1fa-cf11-47b8-8ec5-97b1fddbe2bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>getbowtied_new_product</value>
      <webElementGuid>01641b0a-c57e-41c6-ade3-3d592dcf962f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New!</value>
      <webElementGuid>9897e3a8-aceb-4e38-a492-096bd90582a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sticky_bottom_anchor&quot;)/ul[@class=&quot;products columns-3 js_animated&quot;]/li[@class=&quot;product type-product post-275 status-publish first instock product_cat-89 shipping-taxable purchasable product-type-simple visible animation_ready animated&quot;]/div[@class=&quot;main-container&quot;]/div[@class=&quot;product_image_wrapper&quot;]/div[@class=&quot;product_badges_wrapper&quot;]/span[@class=&quot;getbowtied_new_product&quot;]</value>
      <webElementGuid>8c921332-5299-4d51-9e11-84120131484f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sticky_bottom_anchor']/ul/li[4]/div/div/div/span</value>
      <webElementGuid>a801ea1e-8dcf-4ea6-8e0e-0f16b4e7cd3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to cart'])[2]/following::span[1]</value>
      <webElementGuid>39183166-4816-4b41-8c6a-7425ea238f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick View'])[2]/following::span[2]</value>
      <webElementGuid>7a61a59c-fd0c-4b70-8f38-82fcddcd8475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sale!'])[3]/preceding::span[1]</value>
      <webElementGuid>5436ac94-9d77-45c3-873e-bb40bd883f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cap'])[2]/preceding::span[2]</value>
      <webElementGuid>69b91d7f-c286-45cb-a7ce-a4cdf8670d51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New!']/parent::*</value>
      <webElementGuid>e079419f-cff2-4b20-a0bc-c1166cea2c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/div/div/span</value>
      <webElementGuid>a7bd063b-74fe-43a2-a257-17cd71f069c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'New!' or . = 'New!')]</value>
      <webElementGuid>d00a40a9-52fd-4925-9f64-8571471d7f45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sticky_bottom_anchor']/ul/li[2]/div/div/div/span</value>
      <webElementGuid>f4afd1de-4acf-4b09-893c-d65e9136238b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='新しいレシピセット'])[3]/following::span[2]</value>
      <webElementGuid>4ec6bdc8-afe1-4fa1-9238-050d73497805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='テンペ'])[3]/following::span[3]</value>
      <webElementGuid>ee440b80-1889-47f2-80fc-8af439cb7e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frozen Tempe Furai Original 400 g'])[1]/preceding::span[1]</value>
      <webElementGuid>aeae92c1-dcbf-41a3-9485-048017c099a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp'])[4]/preceding::span[1]</value>
      <webElementGuid>d7422923-d820-4cf3-b7bd-aa41389126a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/span</value>
      <webElementGuid>f992c1d0-5a61-4fd9-9c4b-8b1b3e0d0240</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
