<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm Password_confirm_user_password-297</name>
   <tag></tag>
   <elementGuidId>f9b67a17-472b-4950-8411-50be404b7ff3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirm_user_password-297']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#confirm_user_password-297</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b2ecd62-c6cb-4693-8bba-59a4297b2a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-form-field valid um-validate-not-matched</value>
      <webElementGuid>cbd7981f-ac43-4469-ae02-a4b957ee8eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b6f04b67-f994-4216-b166-72f04e4dbab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirm_user_password-297</value>
      <webElementGuid>a9a3d7f4-8687-4257-9b79-4f5573fea754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirm_user_password-297</value>
      <webElementGuid>2773c24b-1437-4f14-a8fb-ae84e0075262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm Password</value>
      <webElementGuid>aacd988d-aa8c-45e4-afaf-e5498a984ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>confirm_user_password</value>
      <webElementGuid>9d2360f4-0210-47de-862a-9a8f13cf8860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirm_user_password-297&quot;)</value>
      <webElementGuid>186c55f5-fb15-4626-a12b-55dfb0c0f439</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirm_user_password-297']</value>
      <webElementGuid>244ec54d-0bf4-471d-b8fa-c9bc6bb93ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um_field_297_confirm_user_password']/div[2]/input</value>
      <webElementGuid>bea74191-3231-44ae-aa3b-6274a91ae513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>e6a734f4-01ab-4539-b39c-08f35d9c71eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'confirm_user_password-297' and @id = 'confirm_user_password-297' and @placeholder = 'Confirm Password']</value>
      <webElementGuid>207fba96-1e72-474a-9107-0759a6b53226</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
